### PR TITLE
Fix ruby 2.4 warning message re: Fixnum

### PR DESCRIPTION
**Pull request by mattdoller**
Ruby 2.4 and above will print the deprecation message

    warning: constant ::Fixnum is deprecated

when a Fixnum is referenced.  The solution is to use the Integer
type instead.

### CODE REVIEW

**Comment by mattdoller** [comment]
Hi - any interest in integrating this?  I purposely didn't modify the `VERSION` (the repo says 0.2.0, rubygems most recent release is 0.3.0) - not sure what the next step you'd want.

**Comment by geoffreywiseman** [comment]
Seems pretty reasonable, backward-compatible to boot.

**Comment by geoffreywiseman** [comment]
Merged with code I apparently hadn't pushed, added a couple more small things including some minor dependency updates, released as tbm v0.4. Still lots of dependencies to update, but ... it wasn't causing me any active pain points, so I haven't looked at TBM in a bit. Thanks for the PR.

**Comment by mattdoller** [comment]
@geoffreywiseman - thanks for the tool, use it every day!

**Comment by geoffreywiseman** [comment]
Happy it's getting used (by someone other than me). I'll work on upgrading the rest of the dependencies to much more current versions and add a couple more parameters in v0.5 now that I've remembered that I had some things I wanted to finish up to make this a 1.0. ;)

**Pull request merged**
